name: wize_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.11
  geolocator: ^10.1.1
  flutter_sms:
    path: flutter_sms_fix  # ✅ FIX 1: corrected the path dependency syntax
  flutter_local_notifications: ^17.2.4
  intl: ^0.18.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  firebase_auth: ^5.7.0
  firebase_storage: ^12.4.10
  image_picker: ^1.1.1
  permission_handler: ^11.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true