// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlOt3hi0TaR_lcwkzZ-IDpTP_6gTOb-EI',
    appId: '1:309653991955:web:444e9e8fd0b6a423eb45e6',
    messagingSenderId: '309653991955',
    projectId: 'wize-app-9b52d',
    authDomain: 'wize-app-9b52d.firebaseapp.com',
    storageBucket: 'wize-app-9b52d.firebasestorage.app',
    measurementId: 'G-YCXC10HHLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8TVfNnbfNk1iYSfjt4e6TDqrNPWzi9NA',
    appId: '1:309653991955:android:90ad17105549c5b4eb45e6',
    messagingSenderId: '309653991955',
    projectId: 'wize-app-9b52d',
    storageBucket: 'wize-app-9b52d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxKxEYvJnv_12OhtlV7KxENidaNA6N0hs',
    appId: '1:309653991955:ios:179e990118eddabaeb45e6',
    messagingSenderId: '309653991955',
    projectId: 'wize-app-9b52d',
    storageBucket: 'wize-app-9b52d.firebasestorage.app',
    iosBundleId: 'com.example.accidentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxKxEYvJnv_12OhtlV7KxENidaNA6N0hs',
    appId: '1:309653991955:ios:179e990118eddabaeb45e6',
    messagingSenderId: '309653991955',
    projectId: 'wize-app-9b52d',
    storageBucket: 'wize-app-9b52d.firebasestorage.app',
    iosBundleId: 'com.example.accidentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlOt3hi0TaR_lcwkzZ-IDpTP_6gTOb-EI',
    appId: '1:309653991955:web:aea63dc815231e41eb45e6',
    messagingSenderId: '309653991955',
    projectId: 'wize-app-9b52d',
    authDomain: 'wize-app-9b52d.firebaseapp.com',
    storageBucket: 'wize-app-9b52d.firebasestorage.app',
    measurementId: 'G-BF77WNZ9PV',
  );
}
